
backend:
  name: git-gateway
  repo: labetigr/art-lessons
  branch: main

media_folder: "images/portfolio" # Φάκελος όπου θα αποθηκεύονται οι εικόνες
public_folder: "images/portfolio"

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "images/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Τίτλος Έργου", name: "title", widget: "string"}
      - {label: "Φωτογραφία", name: "image", widget: "image"}
      - {label: "Περιγραφή", name: "body", widget: "markdown"}
